//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportInventoryApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportInventoryDBEntities : DbContext
    {
        private static SportInventoryDBEntities _context;
        public SportInventoryDBEntities()
            : base("name=SportInventoryDBEntities")
        {
        }
        public static SportInventoryDBEntities GetContext()
        {
            if (_context == null)
            {
                _context = new SportInventoryDBEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
